version: '3.10'

services:
  bot:
    build: .
    command: python bot/bot.py
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=itechart_user
      - POSTGRES_PASSWORD=itechart
      - POSTGRES_DB=model_launches
    ports:
      - "5433:5432"

volumes:
  postgres_data:

